version: '3'

networks:
  kv_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
          gateway: "172.24.0.1"

services:
  replica1:
    image: maxpoletaev/kiwi
    container_name: replica1
    command: >
      server
        -node-id=1
        -node-name=replica1
        -grpc-bind-addr=0.0.0.0:3000
        -grpc-public-addr=172.24.2.1:3000
        -grpc-local-addr=127.0.0.1:3000
        -gossip-bind-addr=0.0.0.0:4000
        -gossip-public-addr=172.24.2.1:4000
        -data-dir=/data
        -verbose
    ports:
      - 3001:3000
    networks:
      kv_net:
        ipv4_address: 172.24.2.1
    volumes:
      - ./data/replica1:/data

  replica2:
    depends_on:
      - replica1
    image: maxpoletaev/kiwi
    container_name: replica2
    command: >
      server
        -node-id=2
        -node-name=replica2
        -grpc-bind-addr=0.0.0.0:3000
        -grpc-public-addr=172.24.2.2:3000
        -grpc-local-addr=127.0.0.1:3000
        -gossip-bind-addr=0.0.0.0:4000
        -gossip-public-addr=172.24.2.2:4000
        -join-addr=replica1:3000
        -data-dir=/data
        -verbose
    ports:
      - 3002:3000
    networks:
      kv_net:
        ipv4_address: 172.24.2.2
    volumes:
      - ./data/replica2:/data

  replica3:
    depends_on:
      - replica2
    image: maxpoletaev/kiwi
    container_name: replica3
    command: >
      server
        -node-id=3
        -node-name=replica3
        -grpc-bind-addr=0.0.0.0:3000
        -grpc-public-addr=172.24.2.3:3000
        -grpc-local-addr=127.0.0.1:3000
        -gossip-bind-addr=0.0.0.0:4000
        -gossip-public-addr=172.24.2.3:4000
        -join-addr=replica2:3000
        -data-dir=/data
        -verbose
    ports:
      - 3003:3000
    networks:
      kv_net:
        ipv4_address: 172.24.2.3
    volumes:
      - ./data/replica3:/data
