version: '3'

networks:
  kv_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
          gateway: "172.24.0.1"

services:
  replica1:
    image: maxpoletaev/kivi
    container_name: replica1
    environment:
      - NODE_ID=1
      - NODE_NAME=replica1
      - GRPC_PUBLIC_ADDR=172.24.2.1:3000
      - STORAGE_DATA_ROOT=/data
      - CLUSTER_JOIN_ADDRS=replica2:3000
      - CUSTER_PROBE_INTERVAL=500
      - VERBOSE=true
    ports:
      - 3001:3000
      - 8001:8000
    networks:
      kv_net:
        ipv4_address: 172.24.2.1
    volumes:
      - ./data/replica1:/data

  replica2:
    depends_on:
      - replica1
    image: maxpoletaev/kivi
    container_name: replica2
    environment:
      - NODE_ID=2
      - NODE_NAME=replica2
      - GRPC_PUBLIC_ADDR=172.24.2.2:3000
      - STORAGE_DATA_ROOT=/data
      - CLUSTER_JOIN_ADDRS=replica1:3000
      - CUSTER_PROBE_INTERVAL=500
      - VERBOSE=true
    ports:
      - 3002:3000
      - 8002:8000
    networks:
      kv_net:
        ipv4_address: 172.24.2.2
    volumes:
      - ./data/replica2:/data

  replica3:
    depends_on:
      - replica2
    image: maxpoletaev/kivi
    container_name: replica3
    environment:
      - NODE_ID=3
      - NODE_NAME=replica3
      - GRPC_PUBLIC_ADDR=172.24.2.3:3000
      - STORAGE_DATA_ROOT=/data
      - CLUSTER_JOIN_ADDRS=replica2:3000
      - CUSTER_PROBE_INTERVAL=500
      - VERBOSE=true
    ports:
      - 3003:3000
      - 8003:8000
    networks:
      kv_net:
        ipv4_address: 172.24.2.3
    volumes:
      - ./data/replica3:/data
