// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: storage/lsmtree/proto/state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateChangeType int32

const (
	StateChangeType_SEGMENT_CREATED StateChangeType = 0
	StateChangeType_SEGMENT_FLUSHED StateChangeType = 1
	StateChangeType_SEGMENTS_MERGED StateChangeType = 2
)

// Enum value maps for StateChangeType.
var (
	StateChangeType_name = map[int32]string{
		0: "SEGMENT_CREATED",
		1: "SEGMENT_FLUSHED",
		2: "SEGMENTS_MERGED",
	}
	StateChangeType_value = map[string]int32{
		"SEGMENT_CREATED": 0,
		"SEGMENT_FLUSHED": 1,
		"SEGMENTS_MERGED": 2,
	}
)

func (x StateChangeType) Enum() *StateChangeType {
	p := new(StateChangeType)
	*p = x
	return p
}

func (x StateChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_lsmtree_proto_state_proto_enumTypes[0].Descriptor()
}

func (StateChangeType) Type() protoreflect.EnumType {
	return &file_storage_lsmtree_proto_state_proto_enumTypes[0]
}

func (x StateChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateChangeType.Descriptor instead.
func (StateChangeType) EnumDescriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{0}
}

type MemtableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalFile string `protobuf:"bytes,2,opt,name=wal_file,json=walFile,proto3" json:"wal_file,omitempty"`
}

func (x *MemtableInfo) Reset() {
	*x = MemtableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_lsmtree_proto_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemtableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemtableInfo) ProtoMessage() {}

func (x *MemtableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_lsmtree_proto_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemtableInfo.ProtoReflect.Descriptor instead.
func (*MemtableInfo) Descriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{0}
}

func (x *MemtableInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemtableInfo) GetWalFile() string {
	if x != nil {
		return x.WalFile
	}
	return ""
}

type SSTableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level      int32  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Size       int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	NumRecords int64  `protobuf:"varint,4,opt,name=num_records,json=numRecords,proto3" json:"num_records,omitempty"`
	IndexFile  string `protobuf:"bytes,5,opt,name=index_file,json=indexFile,proto3" json:"index_file,omitempty"`
	DataFile   string `protobuf:"bytes,6,opt,name=data_file,json=dataFile,proto3" json:"data_file,omitempty"`
	BloomFile  string `protobuf:"bytes,7,opt,name=bloom_file,json=bloomFile,proto3" json:"bloom_file,omitempty"`
	MetaFile   string `protobuf:"bytes,8,opt,name=meta_file,json=metaFile,proto3" json:"meta_file,omitempty"`
}

func (x *SSTableInfo) Reset() {
	*x = SSTableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_lsmtree_proto_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSTableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTableInfo) ProtoMessage() {}

func (x *SSTableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_lsmtree_proto_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTableInfo.ProtoReflect.Descriptor instead.
func (*SSTableInfo) Descriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{1}
}

func (x *SSTableInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SSTableInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SSTableInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SSTableInfo) GetNumRecords() int64 {
	if x != nil {
		return x.NumRecords
	}
	return 0
}

func (x *SSTableInfo) GetIndexFile() string {
	if x != nil {
		return x.IndexFile
	}
	return ""
}

func (x *SSTableInfo) GetDataFile() string {
	if x != nil {
		return x.DataFile
	}
	return ""
}

func (x *SSTableInfo) GetBloomFile() string {
	if x != nil {
		return x.BloomFile
	}
	return ""
}

func (x *SSTableInfo) GetMetaFile() string {
	if x != nil {
		return x.MetaFile
	}
	return ""
}

type SegmentCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memtable *MemtableInfo `protobuf:"bytes,1,opt,name=memtable,proto3" json:"memtable,omitempty"`
}

func (x *SegmentCreated) Reset() {
	*x = SegmentCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_lsmtree_proto_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentCreated) ProtoMessage() {}

func (x *SegmentCreated) ProtoReflect() protoreflect.Message {
	mi := &file_storage_lsmtree_proto_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentCreated.ProtoReflect.Descriptor instead.
func (*SegmentCreated) Descriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentCreated) GetMemtable() *MemtableInfo {
	if x != nil {
		return x.Memtable
	}
	return nil
}

type SegmentFlushed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemtableId int64        `protobuf:"varint,1,opt,name=memtable_id,json=memtableId,proto3" json:"memtable_id,omitempty"`
	Sstable    *SSTableInfo `protobuf:"bytes,2,opt,name=sstable,proto3" json:"sstable,omitempty"`
}

func (x *SegmentFlushed) Reset() {
	*x = SegmentFlushed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_lsmtree_proto_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFlushed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFlushed) ProtoMessage() {}

func (x *SegmentFlushed) ProtoReflect() protoreflect.Message {
	mi := &file_storage_lsmtree_proto_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFlushed.ProtoReflect.Descriptor instead.
func (*SegmentFlushed) Descriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentFlushed) GetMemtableId() int64 {
	if x != nil {
		return x.MemtableId
	}
	return 0
}

func (x *SegmentFlushed) GetSstable() *SSTableInfo {
	if x != nil {
		return x.Sstable
	}
	return nil
}

type SegmentsMerged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldSstableIds []int64      `protobuf:"varint,1,rep,packed,name=old_sstable_ids,json=oldSstableIds,proto3" json:"old_sstable_ids,omitempty"`
	NewSstable    *SSTableInfo `protobuf:"bytes,2,opt,name=new_sstable,json=newSstable,proto3" json:"new_sstable,omitempty"`
}

func (x *SegmentsMerged) Reset() {
	*x = SegmentsMerged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_lsmtree_proto_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentsMerged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentsMerged) ProtoMessage() {}

func (x *SegmentsMerged) ProtoReflect() protoreflect.Message {
	mi := &file_storage_lsmtree_proto_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentsMerged.ProtoReflect.Descriptor instead.
func (*SegmentsMerged) Descriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentsMerged) GetOldSstableIds() []int64 {
	if x != nil {
		return x.OldSstableIds
	}
	return nil
}

func (x *SegmentsMerged) GetNewSstable() *SSTableInfo {
	if x != nil {
		return x.NewSstable
	}
	return nil
}

type StateLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp      int64           `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChangeType     StateChangeType `protobuf:"varint,2,opt,name=change_type,json=changeType,proto3,enum=lsm.StateChangeType" json:"change_type,omitempty"`
	SegmentCreated *SegmentCreated `protobuf:"bytes,3,opt,name=segment_created,json=segmentCreated,proto3" json:"segment_created,omitempty"`
	SegmentFlushed *SegmentFlushed `protobuf:"bytes,4,opt,name=segment_flushed,json=segmentFlushed,proto3" json:"segment_flushed,omitempty"`
	SegmentsMerged *SegmentsMerged `protobuf:"bytes,5,opt,name=segments_merged,json=segmentsMerged,proto3" json:"segments_merged,omitempty"`
}

func (x *StateLogEntry) Reset() {
	*x = StateLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_lsmtree_proto_state_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateLogEntry) ProtoMessage() {}

func (x *StateLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storage_lsmtree_proto_state_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateLogEntry.ProtoReflect.Descriptor instead.
func (*StateLogEntry) Descriptor() ([]byte, []int) {
	return file_storage_lsmtree_proto_state_proto_rawDescGZIP(), []int{5}
}

func (x *StateLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StateLogEntry) GetChangeType() StateChangeType {
	if x != nil {
		return x.ChangeType
	}
	return StateChangeType_SEGMENT_CREATED
}

func (x *StateLogEntry) GetSegmentCreated() *SegmentCreated {
	if x != nil {
		return x.SegmentCreated
	}
	return nil
}

func (x *StateLogEntry) GetSegmentFlushed() *SegmentFlushed {
	if x != nil {
		return x.SegmentFlushed
	}
	return nil
}

func (x *StateLogEntry) GetSegmentsMerged() *SegmentsMerged {
	if x != nil {
		return x.SegmentsMerged
	}
	return nil
}

var File_storage_lsmtree_proto_state_proto protoreflect.FileDescriptor

var file_storage_lsmtree_proto_state_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x6c, 0x73, 0x6d, 0x74, 0x72, 0x65,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x73, 0x6d, 0x22, 0x39, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x61, 0x6c, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x61, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x0b, 0x53, 0x53, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c,
	0x6f, 0x6f, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x3f, 0x0a, 0x0e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x73, 0x6d,
	0x2e, 0x4d, 0x65, 0x6d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6d,
	0x65, 0x6d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x0e, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x6d, 0x65, 0x6d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x73,
	0x6d, 0x2e, 0x53, 0x53, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x6b, 0x0a, 0x0e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6f, 0x6c, 0x64, 0x5f,
	0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0d, 0x6f, 0x6c, 0x64, 0x53, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x73,
	0x12, 0x31, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x53, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x53, 0x73, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x22, 0x9e, 0x02, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x35, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x0e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x0f, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46,
	0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x52, 0x0e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46,
	0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x0f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x5f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x64, 0x52, 0x0e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x64, 0x2a, 0x50, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x47, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x53, 0x5f, 0x4d, 0x45,
	0x52, 0x47, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x70, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x65, 0x76,
	0x2f, 0x6b, 0x69, 0x76, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x6c, 0x73,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_lsmtree_proto_state_proto_rawDescOnce sync.Once
	file_storage_lsmtree_proto_state_proto_rawDescData = file_storage_lsmtree_proto_state_proto_rawDesc
)

func file_storage_lsmtree_proto_state_proto_rawDescGZIP() []byte {
	file_storage_lsmtree_proto_state_proto_rawDescOnce.Do(func() {
		file_storage_lsmtree_proto_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_lsmtree_proto_state_proto_rawDescData)
	})
	return file_storage_lsmtree_proto_state_proto_rawDescData
}

var file_storage_lsmtree_proto_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_lsmtree_proto_state_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_storage_lsmtree_proto_state_proto_goTypes = []interface{}{
	(StateChangeType)(0),   // 0: lsm.StateChangeType
	(*MemtableInfo)(nil),   // 1: lsm.MemtableInfo
	(*SSTableInfo)(nil),    // 2: lsm.SSTableInfo
	(*SegmentCreated)(nil), // 3: lsm.SegmentCreated
	(*SegmentFlushed)(nil), // 4: lsm.SegmentFlushed
	(*SegmentsMerged)(nil), // 5: lsm.SegmentsMerged
	(*StateLogEntry)(nil),  // 6: lsm.StateLogEntry
}
var file_storage_lsmtree_proto_state_proto_depIdxs = []int32{
	1, // 0: lsm.SegmentCreated.memtable:type_name -> lsm.MemtableInfo
	2, // 1: lsm.SegmentFlushed.sstable:type_name -> lsm.SSTableInfo
	2, // 2: lsm.SegmentsMerged.new_sstable:type_name -> lsm.SSTableInfo
	0, // 3: lsm.StateLogEntry.change_type:type_name -> lsm.StateChangeType
	3, // 4: lsm.StateLogEntry.segment_created:type_name -> lsm.SegmentCreated
	4, // 5: lsm.StateLogEntry.segment_flushed:type_name -> lsm.SegmentFlushed
	5, // 6: lsm.StateLogEntry.segments_merged:type_name -> lsm.SegmentsMerged
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_storage_lsmtree_proto_state_proto_init() }
func file_storage_lsmtree_proto_state_proto_init() {
	if File_storage_lsmtree_proto_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_lsmtree_proto_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemtableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_lsmtree_proto_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSTableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_lsmtree_proto_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_lsmtree_proto_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFlushed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_lsmtree_proto_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentsMerged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_lsmtree_proto_state_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_lsmtree_proto_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_lsmtree_proto_state_proto_goTypes,
		DependencyIndexes: file_storage_lsmtree_proto_state_proto_depIdxs,
		EnumInfos:         file_storage_lsmtree_proto_state_proto_enumTypes,
		MessageInfos:      file_storage_lsmtree_proto_state_proto_msgTypes,
	}.Build()
	File_storage_lsmtree_proto_state_proto = out.File
	file_storage_lsmtree_proto_state_proto_rawDesc = nil
	file_storage_lsmtree_proto_state_proto_goTypes = nil
	file_storage_lsmtree_proto_state_proto_depIdxs = nil
}
